server:
  port: 3020

spring:
  main:
    banner-mode: console
  banner:
    location: classpath:banner/banner.txt
  application:
    name: epl-notifications-manager
  profiles:
    active:
      - dev
